Cleaned up API key check and such

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -65,14 +65,6 @@ jobs:
           CI: true
 
       # Automatic Build
-      - name: Verify Environment Variables for Build
-        run: |
-          if [ -z "${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY || (github.event_name == 'pull_request' && 'AIzaSy_PR_BUILD_MOCK_KEY_12345') || '' }}" ]; then
-            echo "::error::REACT_APP_GOOGLE_MAPS_API_KEY is not defined!"
-            exit 1
-          fi
-
-
       - name: Build frontend production bundle
         run: npm run build
         env:
@@ -84,6 +76,15 @@ jobs:
         run: |
           test -f build/index.html || { echo "Missing index.html!"; exit 1; }
           test -d build/assets || { echo "Missing static asset directory!"; exit 1; }
+
+          echo "Checking if API Key is in the build"
+          if grep -q "AIza" build/assets/*.js; then
+            echo "Google Maps API key successfully injected into build assets."
+          else
+            echo "::error::Build verification failed: API key was not baked into build/assets/*.js (found undefined or missing)."
+            exit 1
+          fi
+
           echo "Build verification successful: production bundle is complete."
           ls -lh build/
 
